require ('../global_const');
require ('./components/conformsTo.js');
require ('./components/extractFieldsTest.js');
require ('./components/isActiveRecordTest.js');
require ('./components/isNotNullIslandRelated.js');
require ('./components/recordHasIdAndPropertiesTest.js');
require ('./components/recordHasNameTest.js');
require ('./components/sqliteStream.js');
require ('./hierarchyFinderTest.js');
require ('./importStreamTest.js');
require ('./peliasDocGeneratorsTest.js');
require ('./readStreamTest.js');
require ('./schema.js');
require ('./module.js');
require ('./bundleList.js');
require('./functional.js');
